Task06
Eliseeev/react-20230-11-09 pull request #7
Opened 2023-12-03 18:06 UTC by Eliseeev

2023-12-04 15:12 UTC, SArchieEdu requested changes

2023-12-04 15:12 UTC, SArchieEdu commented on pages/restaurants-page/components.jsx
> +    const [newTheme, setNewTheme] = useState('')
любое изменение темы будут перерендеривать всю страницу, профит от контекста уменьшается. Лучше использовать псевдородители как в лекции

2023-12-05 13:42 UTC, Eliseeev commented
Случайно загрузил изменения в ветке 5 в ветку 6. Вроде исправил. В 5 ветке сделал изменения и замёржил

2023-12-06 15:37 UTC, Eliseeev commented
Возникли конфликты - применил git config pull.rebase false)

2023-12-07 15:11 UTC, SArchieEdu approved these changes

2023-12-07 15:13 UTC, merged